[package]
name = "phenolrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "phenolrs"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.20.0"
tokio = { version = "1", features = ["full"] }
bytes = "1.4.0"
byteorder = "1.4.3"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
reqwest = { version= "0.11.16", features = ["json", "rustls-tls-manual-roots"] }
log = "0.4"
base64 = "0.21.2"
rand = "0.8.5"

[dependencies.pyo3]
version = "0.20.2"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]