FROM ghcr.io/pyo3/maturin

RUN apt-get update && apt-get install -y openssl libssl-dev openssh-client

# Add GitHub to known_hosts
RUN mkdir -p ~/.ssh && \
    ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN --mount=type=secret,id=ssh_key \
    mkdir -p /root/.ssh && \
    cp /run/secrets/ssh_key /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa

ENTRYPOINT ["/usr/bin/maturin"]