version: 2.1

executors:
  generate-executor:
    machine:
      image: ubuntu-2204:2024.01.1
    working_directory: ~/project

workflows:
  version: 2
  ci:
    jobs:
      - lint-python
      - lint-rust
      - build
      - test-rust
      - test-python:
          requires:
            - build


jobs:
  lint-python:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - restore_cache:
          key: py_lint_cache
      - run: |
          pip install -r dev-requirements.txt
      - run:
          name: Black
          command: black --check --verbose --diff --color ./python
      - run:
          name: Mypy
          command: mypy ./python
      - run:
          name: Flake8
          command: flake8 python
      - run:
          name: Bandit
          command: bandit -r ./python/phenolrs
      - save_cache:
          key: py_lint_cache
          paths:
            - ~/.local
            - ~/.cache/pip
  lint-rust:
    docker:
      - image: cimg/rust:1.75
    steps:
      - checkout
      - run:
          name: Install clippy
          command: rustup component add clippy
      - run:
          name: Set flags
          command: export RUSTFLAGS="-Dwarnings"
      - run:
          name: clippy
          command: cargo clippy
      - run:
          name: fmt
          command: cargo fmt --check
  build:
    executor: generate-executor
    steps:
      - checkout
      - run:
          name: Build builder image
          command: docker build -t phenolrs-builder:latest -f Dockerfile-build .
      - run:
          name: Build release
          command: docker run --rm -v $(pwd):/io phenolrs-builder:latest build --interpreter python3.10
      - persist_to_workspace:
          root: ~/project/target
          paths:
            - wheels

  test-rust:
    docker:
      - image: cimg/rust:1.75
    steps:
      - checkout
      - run:
          name: Cargo build
          command: cargo build --no-default-features
      - run:
          name: Cargo Test
          command: cargo test
  test-python:
    executor: generate-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/target
      - run:
          name: Install Phenol
          command: pip install phenolrs --find-links ./target/wheels
      - run:
          name: Install Arango tools deb
          command: (yes || true) | sudo dpkg -i ./tests/utilities/arangodb3-client_3.10.1-1_amd64.deb
      - run:
          name: Start Database
          command: ./docker/start_db.sh
          environment:
            STARTER_MODE: cluster
            DOCKER_IMAGE: docker.io/arangodb/arangodb:3.11
      - run:
          name: Run tests
          command: pytest --url http://172.28.0.1:8529