name: Build Phenolrs Wheel

on:
  pull_request:

jobs:
  build-linux-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y libssl-dev
          fi
          pip install build maturin twine

      - name: Build the package
        run: python -m build

      - name: ls
        run: ls dist/*

      - name: Pip install from wheel
        run: pip install dist/*.whl

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
        architecture: [x86_64, arm64] # Only applied to macOS

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          brew install openssl
          pip install build maturin twine

      - name: Build the package
        run: |
          if [[ "${{ matrix.architecture }}" == "x86_64" ]]; then
            CFLAGS="-arch x86_64" python -m build
          elif [[ "${{ matrix.architecture }}" == "arm64" ]]; then
            CFLAGS="-arch arm64" python -m build
          fi

      - name: ls
        run: ls dist/*

      - name: Pip install from wheel
        run: pip install dist/*.whl
