name: Build Phenolrs Wheel

on:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
          pip install build maturin twine

      - name: Build the package
        run: python -m build

      - name: ls
        run: ls dist/*

      - name: Pip install from wheel
        run: pip install dist/*.whl

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install build maturin twine

      - name: Build the package
        run: python -m build

      - name: ls
        run: ls dist/*

      - name: Pip install from wheel
        run: Get-ChildItem -Path dist -Filter *.whl | ForEach-Object { pip install $_.FullName }
        shell: powershell

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-12]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          brew install openssl
          pip install build maturin twine

      - name: Build the package
        run: |
          if [[ "${{ matrix.os }}" == "macos-12" ]]; then
            CFLAGS="-arch x86_64" python -m build
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            CFLAGS="-arch arm64" python -m build
          fi

      - name: ls
        run: ls dist/*

      - name: Pip install from wheel
        run: pip install dist/*.whl
