name: Release Phenolrs

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode (build only, no publish)'
        required: true
        type: boolean
        default: false
  release:
    types: [published]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
          pip install build maturin twine
          rustup target add ${{ matrix.target }}

      - name: Build builder image
        run: docker build -t phenolrs-builder:latest -f Dockerfile-build .

      - name: Build the package
        run: docker run --rm -v $(pwd):/io phenolrs-builder:latest build --out dist --release --sdist --target ${{ matrix.target }} --interpreter python3.10 python3.11 python3.12 python3.13

      - name: List built packages
        run: ls -la dist/*

      - name: Publish to Test PyPi
        if: ${{ !github.event.inputs.test_mode }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_TEST }}
        run: twine upload --verbose --repository testpypi dist/*.whl

      - name: Publish to PyPi
        if: ${{ !github.event.inputs.test_mode }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload --verbose --repository pypi dist/*.whl

  release-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: ${{ matrix.target == 'aarch64-pc-windows-msvc' && 'arm64' || 'x64' }}

      - name: Install dependencies
        run: |
          pip install build maturin twine
          rustup target add ${{ matrix.target }}

      - name: Build the package
        env:
          OPENSSL_DIR: C:/Program Files/OpenSSL-Win64
          OPENSSL_INCLUDE_DIR: C:/Program Files/OpenSSL-Win64/include
          OPENSSL_LIB_DIR: C:/Program Files/OpenSSL-Win64/lib
        run: maturin build --out dist --release --sdist --target ${{ matrix.target }} --interpreter python3.10 python3.11 python3.12 python3.13

      - name: List built packages
        run: dir dist

      - name: Publish to Test PyPi
        if: ${{ !github.event.inputs.test_mode }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_TEST }}
        run: twine upload --verbose --repository testpypi dist\*.whl

      - name: Publish to PyPi
        if: ${{ !github.event.inputs.test_mode }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload --verbose --repository pypi dist\*.whl

  release-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          brew install openssl
          pip install build maturin twine
          rustup target add ${{ matrix.target }}

      - name: Build the package
        env:
          OPENSSL_DIR: /usr/local/opt/openssl@3
          OPENSSL_INCLUDE_DIR: /usr/local/opt/openssl@3/include
          OPENSSL_LIB_DIR: /usr/local/opt/openssl@3/lib
        run: maturin build --out dist --release --sdist --target ${{ matrix.target }} --interpreter python3.10 python3.11 python3.12 python3.13

      - name: List built packages
        run: ls -la dist/*

      - name: Publish to Test PyPi
        if: ${{ !github.event.inputs.test_mode }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_TEST }}
        run: twine upload --verbose --repository testpypi dist/*.whl

      - name: Publish to PyPi
        if: ${{ !github.event.inputs.test_mode }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload --verbose --repository pypi dist/*.whl
